version: "2"
run:
  concurrency: 4
  allow-parallel-runners: true
  allow-serial-runners: true
linters:
  default: all
  disable:
    - bodyclose
    - containedctx
    - copyloopvar
    - cyclop
    - depguard
    - dupl
    - dupword
    - embeddedstructfieldcheck
    - err113
    - errcheck
    - errchkjson
    - errorlint
    - exhaustive
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funcorder
    - funlen
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocritic
    - gocyclo
    - godoclint
    - godot
    - godox
    - gosec
    - govet
    - ireturn
    - lll
    - maintidx
    - mnd
    - nakedret
    - nestif
    - nilnil
    - nlreturn
    - noctx
    - noinlineerr
    - nonamedreturns
    - paralleltest
    - perfsprint
    - prealloc
    - protogetter
    - revive
    - tagliatelle
    - testpackage
    - thelper
    - usestdlibvars
    - usetesting
    - varnamelen
    - whitespace
    - wrapcheck
    - wsl
    - wsl_v5
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - demo/*
formatters:
  exclusions:
    generated: lax
