on:
  pull_request:
  push:
    branches:
      - main
name: Build
permissions:
  contents: read
jobs:
  changes:
    runs-on: ubuntu-latest
    # Required permissions
    permissions:
      pull-requests: read
    # Set job outputs to values from filter step
    outputs:
      go: ${{ steps.filter.outputs.go }}
      python: ${{ steps.filter.outputs.python }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v4
      id: filter
      with:
        filters: |
          go:
            - 'go/**'
          python:
            - 'python/**'
  golangci-lint:
    needs: changes
    if: ${{ needs.changes.outputs.go == 'true' }}
    name: Go Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: './go/go.mod'
          cache-dependency-path: './go/go.sum'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v9
        with:
          version: v2.9.0
          working-directory: ./go
  go-build-test:
    needs: ["changes", "golangci-lint"]
    if: ${{ needs.changes.outputs.go == 'true' }}
    name: Go Build + Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
      - name: Install Go
        uses: actions/setup-go@v6
        with:
          go-version-file: './go/go.mod'
          cache-dependency-path: './go/go.sum'
          check-latest: true
          cache: true
      - name: Test
        working-directory: ./go
        run: |
          export PATH=$PATH:$HOME/bin:$HOME/go/bin
          make test
